import {
  ProjectCreatedPayload as ContractsProjectCreatedPayloadSchema,
  ProjectMetaUpdatedPayload as ContractsProjectMetaUpdatedPayloadSchema,
  ProjectDeletedPayload as ContractsProjectDeletedPayloadSchema,
  BattleCreatedPayload as ContractsBattleCreatedPayloadSchema,
  BattleMetaUpdatedPayload as ContractsBattleMetaUpdatedPayloadSchema,
  BattleConditionAddedPayload as ContractsBattleConditionAddedPayloadSchema,
  BattleConditionUpdatedPayload as ContractsBattleConditionUpdatedPayloadSchema,
  BattleConditionStruckPayload as ContractsBattleConditionStruckPayloadSchema,
  BattlePhaseChangedPayload as ContractsBattlePhaseChangedPayloadSchema,
  BattleOrchestratorSetPayload as ContractsBattleOrchestratorSetPayloadSchema,
  BattleDeletedPayload as ContractsBattleDeletedPayloadSchema,
  BattlePrioritySetPayload as ContractsBattlePrioritySetPayloadSchema,
  BattleThreadGroupsSetPayload as ContractsBattleThreadGroupsSetPayloadSchema,
  ProjectPrioritySetPayload as ContractsProjectPrioritySetPayloadSchema,
  QueueEntryAddedPayload as ContractsQueueEntryAddedPayloadSchema,
  QueueEntryRemovedPayload as ContractsQueueEntryRemovedPayloadSchema,
  QueueEntrySkippedPayload as ContractsQueueEntrySkippedPayloadSchema,
  QueueLapResetPayload as ContractsQueueLapResetPayloadSchema,
  QueueActionStartedPayload as ContractsQueueActionStartedPayloadSchema,
  QueueActionWakeRuleSetPayload as ContractsQueueActionWakeRuleSetPayloadSchema,
  QueueActionSettledPayload as ContractsQueueActionSettledPayloadSchema,
  QueueActionClearedPayload as ContractsQueueActionClearedPayloadSchema,
  ThreadCreatedPayload as ContractsThreadCreatedPayloadSchema,
  ThreadTurnQueueUpdatedPayload as ContractsThreadTurnQueueUpdatedPayloadSchema,
  ThreadArchivedPayload as ContractsThreadArchivedPayloadSchema,
  ThreadSettledPayload as ContractsThreadSettledPayloadSchema,
  ThreadMetaUpdatedPayload as ContractsThreadMetaUpdatedPayloadSchema,
  ThreadRuntimeModeSetPayload as ContractsThreadRuntimeModeSetPayloadSchema,
  ThreadInteractionModeSetPayload as ContractsThreadInteractionModeSetPayloadSchema,
  ThreadDeletedPayload as ContractsThreadDeletedPayloadSchema,
  ThreadUnarchivedPayload as ContractsThreadUnarchivedPayloadSchema,
  ThreadUnsettledPayload as ContractsThreadUnsettledPayloadSchema,
  ThreadSnoozedPayload as ContractsThreadSnoozedPayloadSchema,
  ThreadUnsnoozedPayload as ContractsThreadUnsnoozedPayloadSchema,
  ThreadPinnedPayload as ContractsThreadPinnedPayloadSchema,
  ThreadUnpinnedPayload as ContractsThreadUnpinnedPayloadSchema,
  ThreadPinReorderedPayload as ContractsThreadPinReorderedPayloadSchema,
  ThreadMessageSentPayload as ContractsThreadMessageSentPayloadSchema,
  ThreadProposedPlanUpsertedPayload as ContractsThreadProposedPlanUpsertedPayloadSchema,
  ThreadSessionSetPayload as ContractsThreadSessionSetPayloadSchema,
  ThreadTurnDiffCompletedPayload as ContractsThreadTurnDiffCompletedPayloadSchema,
  ThreadRevertedPayload as ContractsThreadRevertedPayloadSchema,
  ThreadActivityAppendedPayload as ContractsThreadActivityAppendedPayloadSchema,
  ThreadTurnStartRequestedPayload as ContractsThreadTurnStartRequestedPayloadSchema,
  ThreadTurnInterruptRequestedPayload as ContractsThreadTurnInterruptRequestedPayloadSchema,
  ThreadApprovalResponseRequestedPayload as ContractsThreadApprovalResponseRequestedPayloadSchema,
  ThreadCheckpointRevertRequestedPayload as ContractsThreadCheckpointRevertRequestedPayloadSchema,
  ThreadSessionStopRequestedPayload as ContractsThreadSessionStopRequestedPayloadSchema,
} from "@t3tools/contracts";

// Server-internal alias surface, backed by contract schemas as the source of truth.
export const ProjectCreatedPayload = ContractsProjectCreatedPayloadSchema;
export const ProjectMetaUpdatedPayload = ContractsProjectMetaUpdatedPayloadSchema;
export const ProjectDeletedPayload = ContractsProjectDeletedPayloadSchema;

export const BattleCreatedPayload = ContractsBattleCreatedPayloadSchema;
export const BattleMetaUpdatedPayload = ContractsBattleMetaUpdatedPayloadSchema;
export const BattleConditionAddedPayload = ContractsBattleConditionAddedPayloadSchema;
export const BattleConditionUpdatedPayload = ContractsBattleConditionUpdatedPayloadSchema;
export const BattleConditionStruckPayload = ContractsBattleConditionStruckPayloadSchema;
export const BattlePhaseChangedPayload = ContractsBattlePhaseChangedPayloadSchema;
export const BattleOrchestratorSetPayload = ContractsBattleOrchestratorSetPayloadSchema;
export const BattleDeletedPayload = ContractsBattleDeletedPayloadSchema;
export const BattlePrioritySetPayload = ContractsBattlePrioritySetPayloadSchema;
export const BattleThreadGroupsSetPayload = ContractsBattleThreadGroupsSetPayloadSchema;

export const ProjectPrioritySetPayload = ContractsProjectPrioritySetPayloadSchema;
export const QueueEntryAddedPayload = ContractsQueueEntryAddedPayloadSchema;
export const QueueEntryRemovedPayload = ContractsQueueEntryRemovedPayloadSchema;
export const QueueEntrySkippedPayload = ContractsQueueEntrySkippedPayloadSchema;
export const QueueLapResetPayload = ContractsQueueLapResetPayloadSchema;
export const QueueActionStartedPayload = ContractsQueueActionStartedPayloadSchema;
export const QueueActionWakeRuleSetPayload = ContractsQueueActionWakeRuleSetPayloadSchema;
export const QueueActionSettledPayload = ContractsQueueActionSettledPayloadSchema;
export const QueueActionClearedPayload = ContractsQueueActionClearedPayloadSchema;

export const ThreadCreatedPayload = ContractsThreadCreatedPayloadSchema;
export const ThreadTurnQueueUpdatedPayload = ContractsThreadTurnQueueUpdatedPayloadSchema;
export const ThreadArchivedPayload = ContractsThreadArchivedPayloadSchema;
export const ThreadSettledPayload = ContractsThreadSettledPayloadSchema;
export const ThreadMetaUpdatedPayload = ContractsThreadMetaUpdatedPayloadSchema;
export const ThreadRuntimeModeSetPayload = ContractsThreadRuntimeModeSetPayloadSchema;
export const ThreadInteractionModeSetPayload = ContractsThreadInteractionModeSetPayloadSchema;
export const ThreadDeletedPayload = ContractsThreadDeletedPayloadSchema;
export const ThreadUnarchivedPayload = ContractsThreadUnarchivedPayloadSchema;
export const ThreadUnsettledPayload = ContractsThreadUnsettledPayloadSchema;
export const ThreadSnoozedPayload = ContractsThreadSnoozedPayloadSchema;
export const ThreadUnsnoozedPayload = ContractsThreadUnsnoozedPayloadSchema;
export const ThreadPinnedPayload = ContractsThreadPinnedPayloadSchema;
export const ThreadUnpinnedPayload = ContractsThreadUnpinnedPayloadSchema;
export const ThreadPinReorderedPayload = ContractsThreadPinReorderedPayloadSchema;

export const MessageSentPayloadSchema = ContractsThreadMessageSentPayloadSchema;
export const ThreadProposedPlanUpsertedPayload = ContractsThreadProposedPlanUpsertedPayloadSchema;
export const ThreadSessionSetPayload = ContractsThreadSessionSetPayloadSchema;
export const ThreadTurnDiffCompletedPayload = ContractsThreadTurnDiffCompletedPayloadSchema;
export const ThreadRevertedPayload = ContractsThreadRevertedPayloadSchema;
export const ThreadActivityAppendedPayload = ContractsThreadActivityAppendedPayloadSchema;

export const ThreadTurnStartRequestedPayload = ContractsThreadTurnStartRequestedPayloadSchema;
export const ThreadTurnInterruptRequestedPayload =
  ContractsThreadTurnInterruptRequestedPayloadSchema;
export const ThreadApprovalResponseRequestedPayload =
  ContractsThreadApprovalResponseRequestedPayloadSchema;
export const ThreadCheckpointRevertRequestedPayload =
  ContractsThreadCheckpointRevertRequestedPayloadSchema;
export const ThreadSessionStopRequestedPayload = ContractsThreadSessionStopRequestedPayloadSchema;
